# Generated by Django 3.1.4 on 2021-01-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210114_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connect',
            options={},
        ),
    ]
