# Generated by Django 3.1.4 on 2021-01-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210115_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connect',
            options={'managed': False},
        ),
    ]
