# Generated by Django 3.1.4 on 2021-01-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_connect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connect',
            options={'managed': False},
        ),
    ]
