# Generated by Django 3.1.4 on 2021-01-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_connect_connect_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='connect_rate',
            field=models.CharField(blank=True, default='0', max_length=45),
        ),
    ]
