# Generated by Django 3.1.4 on 2021-01-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20210113_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='connect',
        ),
    ]
